src/Entity/JobOffer.php
<?php

namespace App\Entity;

use App\Repository\JobOfferRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: JobOfferRepository::class)]
class JobOffer
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $reference = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $description = null;

    #[ORM\Column(nullable: true)]
    private ?bool $active = true;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $notes = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $jobTitle = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $location = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $closingDate = null;

    #[ORM\Column(nullable: true)]
    private ?int $salary = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $createdDate = null;


    #[ORM\OneToMany(targetEntity: Candidature::class, mappedBy: 'jobOffer', orphanRemoval: true)]
    private Collection $Candidature;

    #[ORM\ManyToOne(inversedBy: 'jobOffers')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Client $Client = null;

    #[ORM\ManyToOne(inversedBy: 'jobOffers')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Category $Category = null;

    #[ORM\ManyToOne(inversedBy: 'jobOffers')]
    #[ORM\JoinColumn(nullable: false)]
    private ?JobType $JobType = null;

    public function __construct()
    {
        $this->Candidature = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getReference(): ?string
    {
        return $this->reference;
    }

    public function setReference(?string $reference): static
    {
        $this->reference = $reference;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function isActive(): ?bool
    {
        return $this->active;
    }

    public function setActive(?bool $active): static
    {
        $this->active = $active;

        return $this;
    }

    public function getNotes(): ?string
    {
        return $this->notes;
    }

    public function setNotes(?string $notes): static
    {
        $this->notes = $notes;

        return $this;
    }

    public function getJobTitle(): ?string
    {
        return $this->jobTitle;
    }

    public function setJobTitle(?string $jobTitle): static
    {
        $this->jobTitle = $jobTitle;

        return $this;
    }

    public function getLocation(): ?string
    {
        return $this->location;
    }

    public function setLocation(?string $location): static
    {
        $this->location = $location;

        return $this;
    }

    public function getClosingDate(): ?\DateTimeInterface
    {
        return $this->closingDate;
    }

    public function setClosingDate(?\DateTimeInterface $closingDate): static
    {
        $this->closingDate = $closingDate;

        return $this;
    }

    public function getSalary(): ?int
    {
        return $this->salary;
    }

    public function setSalary(?int $salary): static
    {
        $this->salary = $salary;

        return $this;
    }

    public function getCreatedDate(): ?\DateTimeInterface
    {
        return $this->createdDate;
    }

    public function setCreatedDate(?\DateTimeInterface $createdDate): static
    {
        $this->createdDate = $createdDate;

        return $this;
    }


    /**
     * @return Collection<int, Candidature>
     */
    public function getCandidature(): Collection
    {
        return $this->Candidature;
    }

    public function addCandidature(Candidature $candidature): static
    {
        if (!$this->Candidature->contains($candidature)) {
            $this->Candidature->add($candidature);
            $candidature->setJobOffer($this);
        }

        return $this;
    }

    public function removeCandidature(Candidature $candidature): static
    {
        if ($this->Candidature->removeElement($candidature)) {
            // set the owning side to null (unless already changed)
            if ($candidature->getJobOffer() === $this) {
                $candidature->setJobOffer(null);
            }
        }

        return $this;
    }

    public function getClient(): ?Client
    {
        return $this->Client;
    }

    public function setClient(?Client $Client): static
    {
        $this->Client = $Client;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->Category;
    }

    public function setCategory(?Category $Category): static
    {
        $this->Category = $Category;

        return $this;
    }

    public function getJobType(): ?JobType
    {
        return $this->JobType;
    }

    public function setJobType(?JobType $JobType): static
    {
        $this->JobType = $JobType;

        return $this;
    }

    public function __toString(): string
    {
        return $this->reference;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\UniqueConstraint(name: 'UNIQ_IDENTIFIER_EMAIL', fields: ['email'])]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180)]
    private ?string $email = null;

    /**
     * @var list<string> The user roles
     */
    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\OneToOne(mappedBy: 'User', cascade: ['persist', 'remove'])]
    private ?Candidat $candidat = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     *
     * @return list<string>
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    /**
     * @param list<string> $roles
     */
    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getCandidat(): ?Candidat
    {
        return $this->candidat;
    }

    public function setCandidat(Candidat $candidat): static
    {
        // set the owning side of the relation if necessary
        if ($candidat->getUser() !== $this) {
            $candidat->setUser($this);
        }

        $this->candidat = $candidat;

        return $this;
    }
}

src/Controller/HomeController.php
<?php

namespace App\Controller;

use App\Entity\JobOffer;
use App\Repository\JobOfferRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class HomeController extends AbstractController
{
    #[Route('/', name: 'app_home')]
    public function index(JobOfferRepository $jobOfferRepository): Response
    {
        $jobOffers = $jobOfferRepository->findAll();

        return $this->render(
            'home/index.html.twig',
            [
                'jobOffers' => $jobOffers,
            ]
        );
    }

    #[Route('/compagny', name: 'app_compagny')]
    public function compagny(): Response
    {
        return $this->render(
            'home/compagny.html.twig',
            []
        );
    }

    #[Route('/loginn', name: 'app_loginn')]
    public function login(): Response
    {
        return $this->render(
            'home/login.html.twig',
            []
        );
    }

    #[Route('/registerr', name: 'app_registerr')]
    public function registerr(): Response
    {
        return $this->render(
            'home/registerr.html.twig',
            []
        );
    }

    // #[Route('/contact', name: 'app_contact')]
    // public function contact(): Response
    // {
    //     return $this->render(
    //         'home/contact.html.twig',
    //         []
    //     );
    // }

    #[Route('/profilee', name: 'app_profilee')]
    public function profilee(): Response
    {
        return $this->render(
            'home/profilee.html.twig',
            []
        );
    }

    
}

templates/home/contact.html.twig
{% extends 'base.html.twig' %}

{% block body %}


<div class="base">

    <!-- Page -->
    <div class="page">

        <!-- Page Header-->
        <section class="page-title page-title-bg fixed-bg overlay dark-5 padding-top-160 padding-bottom-80">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <h2 class="white-text">Feel free to contact us</h2>
                        <span class="white-text">for any questions or demands</span>
                        <ol class="breadcrumb">
                            <li><a href="#!">Home</a></li>
                            <li class="active">Contact</li>
                        </ol>
                    </div>
                </div>
            </div>
        </section>

        <!-- Page Content-->
        <form method="POST" action="#!" accept-charset="UTF-8" id="formContact" class="light-gray-bg">
            <input name="_token" type="hidden" value="">
            <input name="job_id" type="hidden" value="">
            <section class="section-padding">
                <div class="container">
                    <div class="text-center mb-80">
                        <h2 class="section-title text-uppercase">Drop us a line</h2>
                        <p class="section-sub text-center">Whether your needs, desires or wishes are urgent or a little less, they will all be taken care of with the some efficiency by us.</p>
                    </div>

                    <div class="row">
                        <div id="contactForm" class="col-xs-12 col-sm-12 col-md-8">
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="input-field">
                                        <input required="required" name="firstname" type="text">
                                        <label for="firstname">First name</label>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="input-field">
                                        <input required="required" name="lastname" type="text">
                                        <label for="lastname">Last name</label>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="input-field">
                                        <input required="required" name="email" type="email">
                                        <label for="email">Email</label>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="input-field">
                                        <input required="required" name="phone" type="tel">
                                        <label for="phone">Phone Number</label>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="input-field">
                                        <textarea class="materialize-textarea" required="required" name="message" cols="50" rows="10"></textarea>
                                        <label for="message">Message</label>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-xs-12 col-md-6 col-md-offset-3">
                                    <button type="submit"
                                            name="submit"
                                            class="btn btn-block gradient primary waves-effect waves-light submit-button">
                                        Send Message
                                    </button>
                                </div>
                            </div>
                        </div>

                        <div class="col-xs-12 col-sm-12 col-md-4 contact-info mt-40">

                            <address>
                                <i class="material-icons brand-color">&#xE55F;</i>
                                <div class="address">
                                    <p>Luxury Services is based in Roanne, on Loire department</p>
                                </div>
                                <i class="material-icons brand-color">&#xE61C;</i>
                                <div class="phone">
                                    <p>+33 (0) 6 60 06 66 00</p>
                                </div>
                                <i class="material-icons brand-color">&#xE916;</i>
                                <div class="phone">
                                    <p>9 - 22h with 24/7 speaker</p>
                                </div>
                                <i class="material-icons brand-color">&#xE0E1;</i>
                                <div class="mail">
                                    <p><a href="#!">georges[a]luxuryservices.com</a></p>
                                </div>
                            </address>
                        </div>
                    </div>
                </div>
            </section>
        </form>
        <div id="myMap" class="height-350">Gmap here</div>

    </div>

</div>

{% endblock %}

templates/home/index.html.twig
{% extends 'base.html.twig' %}


{% block body %}
	<div
		class="base">

		<!-- Page -->
		<div class="page">
			{# {{ app.user.userIdentifier }} #}

			<!-- RS5.0 Core JS Files -->

			<!-- SLIDER REVOLUTION 5.0 EXTENSIONS  (Load Extensions only on Local File Systems! The following part can be removed on Server for On Demand Loading) -->

			<!-- start revolution slider 5.0 -->
				<section class="rev_slider_wrapper"> <div class="rev_slider materialize-slider">
					<ul>

						<!-- slide 1 start -->
						<li
							data-transition="parallaxtoleft" data-slotamount="default" data-easein="Power4.easeInOut" data-easeout="Power4.easeInOut" data-masterspeed="2000" data-rotate="0" data-fstransition="fade" data-fsmasterspeed="1500" data-fsslotamount="7" data-saveperformance="off">

							<!-- MAIN IMAGE -->
							<img
							src="{{ asset('img/bg1.jpg') }}" alt="" data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat" data-bgparallax="10" class="rev-slidebg" data-no-retina>

							<!-- LAYER NR. 1 -->
							<div class="tp-caption rev-heading tp-resizeme" data-x="center" data-y="center" data-voffset="['-80','-80','-80','-80']" data-fontsize="['60','55','50','45']" data-lineheight="['60','60','55','50']" data-width="none" data-height="none" data-whitespace="nowrap" data-transform_idle="o:1;" data-transform_in="y:[100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:0;s:600;e:Power4.easeInOut;" data-transform_out="y:[100%];s:1000;e:Power2.easeInOut;s:1000;e:Power2.easeInOut;" data-mask_in="x:0px;y:[100%];s:inherit;e:inherit;" data-mask_out="x:inherit;y:inherit;s:inherit;e:inherit;" data-start="800" data-splitin="none" data-splitout="none" data-responsive_offset="on" style="z-index: 5; white-space: nowrap;padding-bottom: 20px;">
								<h1 class="rev-heading text-extrabold white-text text-center">Luxury Services</h1>
							</div>

							<!-- LAYER NR. 2 -->
							<div class="tp-caption tp-resizeme rev-subheading" data-x="center" data-y="center" data-voffset="['0','0','10','10']" data-fontsize="['20','20','17','15']" data-width="['1200', '800', '600', '400']" data-height="none" data-whitespace="nowrap" data-transform_idle="o:1;" data-transform_in="y:[100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:0;s:600;e:Power4.easeInOut;" data-transform_out="y:[100%];s:1000;e:Power2.easeInOut;s:1000;e:Power2.easeInOut;" data-mask_in="x:0px;y:[100%];s:inherit;e:inherit;" data-mask_out="x:inherit;y:inherit;s:inherit;e:inherit;" data-start="1000" data-splitin="none" data-splitout="none" data-responsive_offset="on" style="z-index: 6; white-space: nowrap;">
								<h4 class="white-text text-center">Bringing job seekers and employers together for more that 40 years</h4>
							</div>

							<!-- LAYER NR. 3 -->
							<div class="tp-caption tp-resizeme rev-btn" data-x="['center','center','center','center']" data-hoffset="['0','0','0','0']" data-y="['middle','middle','middle','middle']" data-voffset="['130','130','130','150']" data-width="none" data-height="none" data-whitespace="nowrap" data-transform_idle="o:1;" data-style_hover="cursor:default;" data-transform_in="y:[100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:0;s:600;e:Power4.easeInOut;" data-transform_out="y:[100%];s:1000;e:Power2.easeInOut;s:1000;e:Power2.easeInOut;" data-mask_in="x:0px;y:[100%];s:inherit;e:inherit;" data-mask_out="x:inherit;y:inherit;s:inherit;e:inherit;" data-start="1200" data-splitin="none" data-splitout="none" data-responsive_offset="on" style="z-index: 7; white-space: nowrap;">
								<a href="#job-offers" class="btn btn-lg gradient secondary waves-effect waves-light page-scroll">View Jobs</a>
							</div>
						</li>
						<!-- slide 1 end -->

						<!-- slide 2 start -->
						<li
							data-transition="parallaxtoleft" data-slotamount="default" data-easein="Power4.easeInOut" data-easeout="Power4.easeInOut" data-masterspeed="2000" data-rotate="0" data-fstransition="fade" data-fsmasterspeed="1500" data-fsslotamount="7" data-saveperformance="off">

							<!-- MAIN IMAGE -->
							<img
							src="{{ asset('img/bg3.jpg') }}" alt="" data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat" data-bgparallax="10" class="rev-slidebg" data-no-retina>

							<!-- LAYER NR. 1 -->
							<div class="tp-caption rev-heading tp-resizeme" data-x="center" data-y="center" data-voffset="['-80','-80','-80','-80']" data-fontsize="['60','55','50','45']" data-lineheight="['60','60','55','50']" data-width="none" data-height="none" data-whitespace="nowrap" data-transform_idle="o:1;" data-transform_in="y:[100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:0;s:600;e:Power4.easeInOut;" data-transform_out="y:[100%];s:1000;e:Power2.easeInOut;s:1000;e:Power2.easeInOut;" data-mask_in="x:0px;y:[100%];s:inherit;e:inherit;" data-mask_out="x:inherit;y:inherit;s:inherit;e:inherit;" data-start="800" data-splitin="none" data-splitout="none" data-responsive_offset="on" style="z-index: 5; white-space: nowrap;">
								<h1 class="rev-heading text-extrabold white-text text-center">Recruitment & services</h1>
							</div>

							<!-- LAYER NR. 2 -->
							<div class="tp-caption tp-resizeme rev-subheading" data-x="center" data-y="center" data-voffset="['0','0','10','30']" data-fontsize="['20','20','17','15']" data-width="['1200', '800', '600', '400']" data-height="none" data-whitespace="nowrap" data-transform_idle="o:1;" data-transform_in="y:[100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:0;s:600;e:Power4.easeInOut;" data-transform_out="y:[100%];s:1000;e:Power2.easeInOut;s:1000;e:Power2.easeInOut;" data-mask_in="x:0px;y:[100%];s:inherit;e:inherit;" data-mask_out="x:inherit;y:inherit;s:inherit;e:inherit;" data-start="1000" data-splitin="none" data-splitout="none" data-responsive_offset="on" style="z-index: 6; white-space: nowrap;">
								<h4 class="white-text text-center">Bringing job seekers and employers together for more that 40 years</h4>
							</div>

							<!-- LAYER NR. 3 -->
							<div class="tp-caption tp-resizeme rev-btn" data-x="['center','center','center','center']" data-hoffset="['0','0','0','0']" data-y="['middle','middle','middle','middle']" data-voffset="['130','130','140','170']" data-width="none" data-height="none" data-whitespace="nowrap" data-transform_idle="o:1;" data-style_hover="cursor:default;" data-transform_in="y:[100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:0;s:600;e:Power4.easeInOut;" data-transform_out="y:[100%];s:1000;e:Power2.easeInOut;s:1000;e:Power2.easeInOut;" data-mask_in="x:0px;y:[100%];s:inherit;e:inherit;" data-mask_out="x:inherit;y:inherit;s:inherit;e:inherit;" data-start="1200" data-splitin="none" data-splitout="none" data-responsive_offset="on" style="z-index: 7; white-space: nowrap;">
								<a href="#job-offers" class="btn btn-lg gradient secondary waves-effect waves-light page-scroll">View Jobs</a>
							</div>

						</li>
						<!-- slide 2 end -->

					</ul>
				</div>
				<!-- end revolution slider -->
			</section>
			<!-- end of slider wrapper -->

			<!-- Page Content-->
			<!--<section class="full-width promo-box brand-bg ptb-50">-->
			<!--<div class="container">-->
			<!---->
			<!--</div>-->
			<!--</section>-->
				<section class="ptb-50 brand-bg"> <div class="container">
					<div class="row">
						<div class="col-md-12 mb-40">
							<div class="promo-info">
								<span class="white-text">Whether you're an employer or a candidate looking for jobs</span>
								<h3 class="white-text text-bold text-uppercase no-margin">WE HAVE THE SOLUTION FOR YOU</h3>
							</div>
							<div class="promo-btn">
								<a href="{{ path('app_contact_new')}}" class="btn border secondary waves-effect waves-light">Contact Us</a>
							</div>
						</div>
					</div>

					<hr class="mt-10 mb-50">

					<div class="text-center">
						<h2 class="section-title primary-text">Who We are</h2>
						<p class="section-sub white-text">Luxury Services is a leading professional recruitment consultancy specialising in the recruitment of permanent, contract and temporary positions on behalf of the world’s top employers.</p>
					</div>
					<br>

					<div class="row">
						<div class="col-sm-6">
							<div id="project-slider" class="carousel slide boot-slider" data-ride="carousel">
								<ol class="carousel-indicators">
									<li data-target="#project-slider" data-slide-to="0" class="active"></li>
									<li data-target="#project-slider" data-slide-to="1"></li>
								</ol>

								<div class="carousel-inner" role="listbox">
									<div class="item active">
										<img class="img-responsive" src="{{ asset('img/slide1.jpg') }}" alt="">
									</div>
									<div class="item">
										<img class="img-responsive" src="{{ asset('img/slide2.jpg') }}" alt="">
									</div>
								</div>

								<a class="left carousel-control" href="#project-slider" role="button" data-slide="prev">
									<span class="fa fa-angle-left" aria-hidden="true"></span>
									<span class="sr-only">Previous</span>
								</a>
								<a class="right carousel-control" href="#project-slider" role="button" data-slide="next">
									<span class="fa fa-angle-right" aria-hidden="true"></span>
									<span class="sr-only">Next</span>
								</a>
							</div>
						</div>
						<div class="col-sm-6">
							<h3 class="primary-text">Our philosophy</h3>
							<p class="white-text">Our role is to work with employers and job seekers to facilitate a successful match. This can range from advising a global company on a candidate sourcing strategy to helping a job seeker find their dream job.</p>
						</div>

						<div class="text-center">
							<a href="{{ path('app_compagny')}}" class="btn gradient secondary waves-effect waves-light mt-40">More about us</a>
						</div>
					</div>
				</div>
			</section>

			<section class="cta-candidate bg-fixed bg-cover overlay dark-5 padding-top-70 padding-bottom-50">
				<div class="container">
					<div class="row">
						<div class="valign-wrapper text-center">
							<div class="hero-intro valign-cell">
								<h2 class="tt-headline clip is-full-width no-margin">
									<span>You are
									</span>
									<span class="tt-words-wrapper">
										<b class="is-visible">Commercial</b>
										<b>Creative</b>
										<b>Marketing & PR</b>
										<b>Technology</b>
										<b>Fashion & luxury</b>
										<b>Retail sales</b>
									</span>
								</h2>
								<h3 class="c-secondary mb-30 no-margin">Sign-up and apply for jobs now</h3>
								<p class="white-text section-sub">Each one of your skills is seen as precious resource to us, each one of your personality traits are considered as an added on value. Joining us is allowing our recruitment expertise and personal guidance to bring the best out in you by choosing the most suited position.</p>

								<a href="{{ path('app_register')}}" class="btn border secondary waves-effect waves-light mt-40">Join us</a>
							</div>
						</div>
					</div>
				</div>
			</section>
			<section id="job-offers" class="section-padding gray-bg">
				<div class="container">
					<div class="text-center mb-40">
						<h2 class="section-title">Job offers</h2>
						<p class="section-sub">Just like our candidates, we offer quality, serious & reliable positions. Come discover them and we will put you in contact with the perfect team for you to form the perfect crew.</p>
					</div>
					<div class="portfolio-container">

						<ul class="portfolio-filter brand-filter text-center">
							<li class="active waves-effect waves-light" data-group="all">All</li>
							<li class=" waves-effect waves-light" data-group="commercial">Commercial</li>
							<li class=" waves-effect waves-light" data-group="retail">Retail sales</li>
							<li class=" waves-effect waves-light" data-group="creative">Creative</li>
							<li class=" waves-effect waves-light" data-group="technology">Technology</li>
							<li class=" waves-effect waves-light" data-group="marketing">Marketing & PR</li>
							<li class=" waves-effect waves-light" data-group="fashion">Fashion & luxury</li>
							<li class=" waves-effect waves-light" data-group="management">Management & HR</li>
						</ul>
							<div class="portfolio portfolio-with-title col-2 gutter mt-30">

								{% for jobOffer in jobOffers %}
									<div class="portfolio-item" data-groups='["all", "{{jobOffer.jobType.type}}"]'>
										<div class="portfolio-wrapper">
											<div class="card job-card">
												<div class="card-content">
													<span class="title">
													<span class="card-title">{{ jobOffer.jobTitle }}</span>
													<span class="ref grey-text">Ref
													{{ jobOffer.reference }}</span>
													<div class="metas mb-20">
														<div class="meta">

															<i class="material-icons">&#xE53E;</i>
															{{ jobOffer.salary }}&euro;</div><div class="meta">

															<i class="material-icons">&#xE916;</i>
															{{ jobOffer.createdDate|date("d/m/Y") }}</div><div class="meta">

															<i class="material-icons">&#xE55F;</i>
															{{ jobOffer.location }}</div></div>

																<p class="truncate-text">{{ jobOffer.description|slice(0,60) }}</p>
														</div>
													<div class="card-action">

													<a class="btn btn-md primary border waves-effect waves-dark" href="{{path('app_job_offer_show', {'id': jobOffer.id}) }}">Details</a>

													<a class="btn btn-md primary waves-effect waves-light" href="#!">Apply</a>
													</div>
												</div>
											</div>
										</div>
									<div class="no-item">
								</div>
							{% endfor %}
						</div>
					</div>


						<div class="text-center">
							<a href="/templates/jobs/index.html" class="btn gradient secondary waves-effect waves-light mt-30">View all job offers</a>
						</div>
					</div>
				</div>
			</section>

		</div>

	</div>


{% endblock %}